### ISSUE TITLE
can't get wikiart.zip to download

### ISSUE THREAD

**Issue by SB2020-eye** [monniert/docExtractor#1]
Hi. Thanks for the great tool!

I can't get the wikiart.zip to download. First I was running the script included in the package, but it would always time out. Then I went directly to [](http://web.fsktm.um.edu.my/~cschan/source/ICIP2017/wikiart.zip), but I get a message (in Chrome) that "this site can't be reached."

Is there any other way to obtain this resource?

Thanks in advance.

**Comment by monniert** [comment]
Hi, thanks for reaching out! I just tried to ping the link in Chrome and the download is starting, can you try again? Let me know if it still doesn't work

Tom

**Comment by SB2020-eye** [comment]
It indeed appears to be downloading now. I'm quite sure it wasn't for a while. Glad it's working. And sorry for the trouble.

**Comment by monniert** [comment]
No problem, I also had hard time to download it completely
