### ISSUE TITLE
Post-processing step

### ISSUE THREAD

**Issue by marouamehri** [monniert/docExtractor#16]
Hi @monniert 

Thank you very much for sharing the code with us.

When running the "tester.py" script, the results are obtained by using only the trained model or the trained model followed by the post-processing step?

Thank you in advance

**Comment by monniert** [comment]
Hi, in `tester.py` the results are the raw output of the model (no post-processing), please see the `seg_evaluator.py` (https://github.com/monniert/docExtractor/blob/master/src/seg_evaluator.py#L138) or `extractor.py` (https://github.com/monniert/docExtractor/blob/master/src/extractor.py#L136) scripts to obtain results with the post-processing step

**Comment by monniert** [comment]
closing the issue, please reopen if needed
