### ISSUE TITLE
quality/resolution of image results

### ISSUE THREAD

**Issue by SB2020-eye** [monniert/docExtractor#2]
Hello again.

The images that result from running docExtractor (as found in the "text" and "illustration" folders) -- should I expect these to be full resolution with respect to the original? Or is some reduction or loss involved?

(I did my own little (if crude) test. Here is a clip resulting from docExtractor:

![Folio_015v_22](https://user-images.githubusercontent.com/56878280/97193129-0bbaa980-177f-11eb-9b8a-3ff70be77a31.jpg)

The file size is 33.7 KB.

Here is a crop I made from the original:

![Folio_015_linetest](https://user-images.githubusercontent.com/56878280/97193434-618f5180-177f-11eb-971b-4b1554acc06b.jpg)

The file size is 70.4 KB.

I confess I don't know enough about digital imagery, how files are saved, etc to know if this concludes anything or not. :) Regardless, my goal is to have crops made using docExtractor that are lossless.)

**Comment by monniert** [comment]
Hi SB2020-eye, indeed I didn't provide much details about the quality of extracted elements, but I can understand lossless extractions are key when working with HD documents:

- the prediction is made at a resolution within 1280x1280 but is then upsampled to match original image dimensions, so the crops are made at full resolution wrt the original image,
- there may be some loss when saving the crop image to disk, especially when saving as a jpg file. There are 2 main options that you can try to avoid losing too much information: i) play with PIL `save` function arguments (line 96-97 in `extractor.py`), you can start by setting `quality=95` and look at the results (see [here](https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html#jpeg) for more information), ii) save images in a lossless format like `png`, you can do that by passing `out_ext='png'` when instanciating the `Extractor` (line 212, `extractor.py`)

Be aware it will take much more space than compressed jpg images, I hope this helps!

**Comment by SB2020-eye** [comment]
This is all very helpful, indeed! Thank you so much!
