### ISSUE TITLE
conda conflicts

### ISSUE THREAD

**Issue by RealNicolasBourbaki** [monniert/docExtractor#21]
Hi guys,

I really like your work and want to use it in my project. But a big problem I have right now is the conda environment... I tried to setup the environment with your ```environment.yml``` but I got a HUGE BUNCH of package conflicts.

Is there anything I'm missing? Or the environment is indeed inconsistent and I can just do it with ```pip``` while ignoring all the conflicts?

I'm using ```Anaconda 4.7.10``` 

Thanks for your time!

Greetings from Germany,
Nicole

**Comment by RealNicolasBourbaki** [comment]
Nevermind, I was using Windows, that's why.

Switched to Linus like any ML scientist would do and no problem exists whatsoever! Thanks again!

**Comment by monniert** [comment]
Hi Nicole, thanks for reaching out and happy it was resolved easily!
Don't hesitate to reach out if you run into any other trouble
Tom
