### ISSUE TITLE
[bug] KeyError: 'filename'

### ISSUE THREAD

**Issue by seekingdeep** [monniert/docExtractor#4]
[input.zip](https://github.com/monniert/docExtractor/files/5611304/input.zip)

```
(docExtractor) home@home-lnx:~/programs/docExtractor$ python src/via_converter.py --input_dir input/ --output_dir output/ --file ./test.json 
Traceback (most recent call last):
  File "src/via_converter.py", line 80, in <module>
    conv.run()
  File "src/via_converter.py", line 36, in run
    img = self.convert(annot)
  File "src/via_converter.py", line 41, in convert
    name = annot['filename']
KeyError: 'filename'
```

**Comment by monniert** [comment]
Thanks for the issue, depending on how you downloaded the json from VIA (as a full project json or simply downloading the `via_region_data.json` file) the structure is not the same, bcaf5c5 should handle both cases and fix this issue

**Comment by seekingdeep** [comment]
commit bcaf5c5 solves this issue, i confirm
