### ISSUE TITLE
[suggestion] save detected regions as vgg-json

### ISSUE THREAD

**Issue by seekingdeep** [monniert/docExtractor#5]
@monniert 

A good suggestion would be to save the predicted regions as a VGG Image Anotator .json file, even if the order of the predicted regions is wrong.

`--output_json ./output/detected.json`
`--ignore_readingorder`

**Comment by monniert** [comment]
agreed, saving the predictions as a text file with coordinates (either via_json format or simple csv) is something I will implement when I have some time
