### ISSUE TITLE
[donate] include FUNDING.yml to accept donations

### ISSUE THREAD

**Issue by seekingdeep** [monniert/docExtractor#7]
This project seems interesting, and in-order to insure the continuity of development and improvement i would suggest adding a `FUNDING.yml` so that you can accept donations.

My main interest in this project:
- Simplicity and straightforwardness: directly input .json files and start training/finetuning. directly predict and output .json file.
- Scalability and efficiency:  the training/predicting data might contain millions of images, therefore it would be reasonable instead of preloading all the data during the training, to only load the data on the fly, meaning the required number of files.

Does these suggestions align with the goal of this project?
Do you accept donations?

**Comment by monniert** [comment]
Thanks I will consider it! Outputing a json with the region coordinates and class is clearly a good feature, I will try to code it when I have some time. I think the other suggestions are not as useful / have lower priority, so if really necessary, I will look at it once I finish my undergoing other projects
